---
title: "Images_and_LinkedIn_Profile(Data_Analysis)"
author: "Allama Ikbal Sijan"
date: "2023-09-12"
output:
  pdf_document: default
  html_document: default
---

```{r Installing & Loacding packages, include=FALSE}
chooseCRANmirror(ind = 1)
install.packages("tidyverse")
install.packages("psych")
install.packages("dplyr")
library(tidyverse)
library(psych)
library(dplyr)
```

## Data Wrangling & Cleaning
```{r Loading dataset, message=FALSE}
df <- read_csv("Data_Clean.csv")
df <- df %>% 
  select(!c(StartDate, EndDate, IPAddress, Status, 
            RecordedDate, LocationLatitude, LocationLongitude, DistributionChannel,Q1))

```

```{r Cleaning dataset}
df <- df %>% slice(-2)
```


```{r Asian man}
asian_man_df <- df %>%
  select(ResponseId, Column1, `Duration (in seconds)`, Progress, UserLanguage, Finished, Attention_check, starts_with("Asian_Man"), starts_with("Demographics"))

asian_man_df <- asian_man_df %>% 
  filter(Asian_Man_1 != "N/A")

colnames(asian_man_df) <- asian_man_df[1,]
asian_man_df <- asian_man_df[-1, ]
colnames(asian_man_df)[7] = "Attention_check"
```

```{r Asian woman}
asian_woman_df <- df %>%
  select(ResponseId, Column1, `Duration (in seconds)`, Progress, UserLanguage, Finished, Attention_check, starts_with("Asian_Woman"), starts_with("Demographics"))

asian_woman_df <- asian_woman_df %>% 
  filter(Asian_Woman_1 != "N/A")

colnames(asian_woman_df) <- asian_woman_df[1,]
asian_woman_df <- asian_woman_df[-1, ]
colnames(asian_woman_df)[7] = "Attention_check"
```

```{r Black Man}
black_man_df <- df %>%
  select(ResponseId, Column1, `Duration (in seconds)`, Progress, UserLanguage, Finished, Attention_check, starts_with("Black_Man"), starts_with("Demographics"))

black_man_df <- black_man_df %>% 
  filter(Black_Man_1 != "N/A")

colnames(black_man_df) <- black_man_df[1,]
black_man_df <- black_man_df[-1, ]
colnames(black_man_df)[7] = "Attention_check"
```

```{r Black Woman}
black_woman_df <- df %>%
  select(ResponseId, Column1, `Duration (in seconds)`, Progress, UserLanguage, Finished, Attention_check, starts_with("Black_Woman"), starts_with("Demographics"))

black_woman_df <- black_woman_df %>% 
  filter(Black_Woman_1 != "N/A")

colnames(black_woman_df) <- black_woman_df[1,]
black_woman_df <- black_woman_df[-1, ]
colnames(black_woman_df)[7] = "Attention_check"
```

```{r Blight Man}
blight_man_df <- df %>%
  select(ResponseId, Column1, `Duration (in seconds)`, Progress, UserLanguage, Finished, Attention_check, starts_with("Blight_Man"), starts_with("Demographics"))

blight_man_df <- blight_man_df %>% 
  filter(Blight_Man_1 != "N/A")

colnames(blight_man_df) <- blight_man_df[1,]
blight_man_df <- blight_man_df[-1, ]
colnames(blight_man_df)[7] = "Attention_check"
```

```{r Blight Woman}
blight_woman_df <- df %>%
  select(ResponseId, Column1, `Duration (in seconds)`, Progress, UserLanguage, Finished, Attention_check, starts_with("Blight_Woman"), starts_with("Demographics"))

blight_woman_df <- blight_woman_df %>% 
  filter(Blight_Woman_1 != "N/A")

colnames(blight_woman_df) <- blight_woman_df[1,]
blight_woman_df <- blight_woman_df[-1, ]
colnames(blight_woman_df)[7] = "Attention_check"
```

```{r Wasian Man}
wasian_man_df <- df %>%
  select(ResponseId, Column1, `Duration (in seconds)`, Progress, UserLanguage, Finished, Attention_check, starts_with("Wasian_Man"), starts_with("Demographics"))

wasian_man_df <- wasian_man_df %>% 
  filter(Wasian_Man_1 != "N/A")

colnames(wasian_man_df) <- wasian_man_df[1,]
wasian_man_df <- wasian_man_df[-1, ]
colnames(wasian_man_df)[7] = "Attention_check"
```

```{r Wasian Woman}
wasian_woman_df <- df %>%
  select(ResponseId, Column1, `Duration (in seconds)`, Progress, UserLanguage, Finished, Attention_check, starts_with("Wasian_Woman"), starts_with("Demographics"))

wasian_woman_df <- wasian_woman_df %>% 
  filter(Wasian_Woman_1 != "N/A")

colnames(wasian_woman_df) <- wasian_woman_df[1,]
wasian_woman_df <- wasian_woman_df[-1, ]
colnames(wasian_woman_df)[7] = "Attention_check"
```

```{r White Man}
white_man_df <- df %>%
  select(ResponseId, Column1, `Duration (in seconds)`, Progress, UserLanguage, Finished, Attention_check, starts_with("White_Man"), starts_with("Demographics"))

white_man_df <- white_man_df %>% 
  filter(White_Man_1 != "N/A")

colnames(white_man_df) <- white_man_df[1,]
white_man_df <- white_man_df[-1, ]
colnames(white_man_df)[7] = "Attention_check"
```

```{r White Woman}
white_woman_df <- df %>%
  select(ResponseId, Column1, `Duration (in seconds)`, Progress, UserLanguage, Finished, Attention_check, starts_with("White_Woman"), starts_with("Demographics"))

white_woman_df <- white_woman_df %>% 
  filter(White_Woman_1 != "N/A")

colnames(white_woman_df) <- white_woman_df[1,]
white_woman_df <- white_woman_df[-1, ]
colnames(white_woman_df)[7] = "Attention_check"
```

```{r stacking the datasets, warning=FALSE}
new_df <- rbind(asian_man_df, asian_woman_df,
                black_man_df, black_woman_df,
                blight_man_df, blight_woman_df,
                wasian_man_df, wasian_woman_df,
                white_man_df, white_woman_df)
```

```{r data cleaning & renaming, warning=FALSE}
new_df = new_df[,!(names(new_df) %in% c("Timing - First Click","Timing - Last Click"))]

colnames(new_df)[8] <- "timing_page_submit_LP"
colnames(new_df)[9] <- "click_count_LP"

colnames(new_df)[10] <- "item1_leader"
colnames(new_df)[11] <- "timing_leader"
colnames(new_df)[12] <- "click_count_leader"

colnames(new_df)[13] <- "item2_independent"
colnames(new_df)[14] <- "timing_independent"
colnames(new_df)[15] <- "click_count_independent"

colnames(new_df)[16] <- "item3_ambitious"
colnames(new_df)[17] <- "timing_ambitious"
colnames(new_df)[18] <- "click_count_ambitious"

colnames(new_df)[19] <- "item4_loyal"
colnames(new_df)[20] <- "timing_loyal"
colnames(new_df)[21] <- "click_count_loyal"

colnames(new_df)[22] <- "item5_sensitive"
colnames(new_df)[23] <- "timing_sensitive"
colnames(new_df)[24] <- "click_count_sensitive"

colnames(new_df)[25] <- "item6_warm"
colnames(new_df)[26] <- "timing_warm"
colnames(new_df)[27] <- "click_count_warm"

colnames(new_df)[28] <- "item7_compassionate"
colnames(new_df)[29] <- "timing_compassionate"
colnames(new_df)[30] <- "click_count_compassionate"

colnames(new_df)[31] <- "item8_adaptable"
colnames(new_df)[32] <- "timing_adaptable"
colnames(new_df)[33] <- "click_count_adaptable"

colnames(new_df)[34] <- "item9_sincere"
colnames(new_df)[35] <- "timing_sincere"
colnames(new_df)[36] <- "click_count_sincere"

colnames(new_df)[37] <- "item10_reliable"
colnames(new_df)[38] <- "timing_reliable"
colnames(new_df)[39] <- "click_count_reliable"

colnames(new_df)[40] <- "item11_truthful"
colnames(new_df)[41] <- "timing_truthful"
colnames(new_df)[42] <- "click_count_truthful"

colnames(new_df)[43] <- "item12_race"
colnames(new_df)[44] <- "timing_race"
colnames(new_df)[45] <- "click_count_race"

colnames(new_df)[46] <- "dem1_age"
colnames(new_df)[47] <- "dem2_gender"
colnames(new_df)[48] <- "dem3_ethnicity"
colnames(new_df)[49] <- "dem3_ethnicity_other"

colnames(new_df)[50] <- "dem4_employment_status"
colnames(new_df)[51] <- "dem5_occupation"

```

```{r removing participants, warning=FALSE}
new_df <- new_df %>% 
  filter(Finished == TRUE & Attention_check == "Digital Marketing Role")
```

```{r factors & numeric, warning=FALSE}
fac_var <- c("Group", "item12_race", "dem2_gender", "dem3_ethnicity", "dem4_employment_status")
new_df <- new_df %>% 
  mutate(across(fac_var, as.factor))

num_var <- c("Duration (in seconds)", "timing_page_submit_LP", "click_count_LP","item1_leader", "timing_leader", "click_count_leader", "item2_independent", "timing_independent", "click_count_independent", "item3_ambitious", "timing_ambitious", "click_count_ambitious", "item4_loyal", "timing_loyal", "click_count_loyal", "item5_sensitive", "timing_sensitive", "click_count_sensitive", "item6_warm", "timing_warm", "click_count_warm", "item7_compassionate", "timing_compassionate", "click_count_compassionate", "item8_adaptable", "timing_adaptable", "click_count_adaptable", "item9_sincere", "timing_sincere", "click_count_sincere", "item10_reliable", "timing_reliable", "click_count_reliable", "item11_truthful", "timing_truthful", "click_count_truthful", "timing_race", "click_count_race", "dem1_age")
new_df <- new_df %>% 
  mutate(across(num_var, as.numeric))
```

## Descriptive statistics
```{r mean, sd & distribution}
describe(new_df)
```
```{r aggregation}
new_df <- new_df %>% 
  mutate(masculinity = (item1_leader + item2_independent + item3_ambitious) / 3,
         femininity = (item4_loyal + item5_sensitive + item6_warm + item7_compassionate) / 4,
         neutral = (item8_adaptable + item9_sincere + item10_reliable + item11_truthful) / 4)

aggregated_scale <- new_df[ , c("masculinity", "femininity", "neutral")]
alpha(aggregated_scale)

## all the aggregated scales highly correlate with the overall scale (highest corr neutral = 0.93)
## so dropping neutral would have the most impact on alpha value, while dropping masculinity or feminity scale would still result in a fair alpha value (alpha >.8)

new_df <- new_df %>% 
  mutate(total_response_time = timing_leader + timing_independent + timing_ambitious + 
           timing_loyal + timing_sensitive + timing_warm + timing_compassionate +
           timing_adaptable + timing_sincere + timing_reliable + timing_truthful)
```
```{r group difference in response time, echo=TRUE}
total_response_time_bygroup <- new_df %>% 
  group_by(Group) %>% 
  summarise(Mean = mean(total_response_time), Sd = sd(total_response_time))
total_response_time_bygroup

item_wise_response_time_bygroup <- new_df %>% 
  group_by(Group) %>% 
  summarise(Mean_timing_leader = mean(timing_leader), Sd_timing_leader = sd(timing_leader),
            Mean_timing_independent = mean(timing_independent), Sd_timing_independent = sd(timing_independent),
            Mean_timing_ambitious = mean(timing_ambitious), Sd_timing_ambitious = sd(timing_ambitious),
            Mean_timing_loyal = mean(timing_loyal), Sd_timing_loyal = sd(timing_loyal),
            Mean_timing_sensitive = mean(timing_sensitive), Sd_timing_sensitive = sd(timing_sensitive),
            Mean_timing_warm = mean(timing_warm), Sd_timing_warm = sd(timing_warm),
            Mean_timing_compassionate = mean(timing_compassionate), Sd_timing_compassionate = sd(timing_compassionate),
            Mean_timing_adaptable = mean(timing_adaptable), Sd_timing_adaptable = sd(timing_adaptable),
            Mean_timing_sincere = mean(timing_sincere), Sd_timing_sincere = sd(timing_sincere),
            Mean_timing_reliable = mean(timing_reliable), Sd_timing_reliable = sd(timing_reliable),
            Mean_timing_truthful = mean(timing_truthful), Sd_timing_truthful = sd(timing_truthful))
item_wise_response_time_bygroup

## histogram
total_response_time_bygroup %>% 
  ggplot(aes(x = Group, y = Mean)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean - Sd, ymax = Mean + Sd),
                width = 0.2, position = position_dodge(width = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item1 leader
item_wise_response_time_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_timing_leader)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_timing_leader - Sd_timing_leader, ymax = Mean_timing_leader + Sd_timing_leader),
                width = 0.2, position = position_dodge(width = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#item2 independent
item_wise_response_time_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_timing_independent)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_timing_independent - Sd_timing_independent, ymax = Mean_timing_independent + Sd_timing_independent),
                width = 0.2, position = position_dodge(width = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item3 ambitious
item_wise_response_time_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_timing_ambitious)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_timing_ambitious - Sd_timing_ambitious, ymax = Mean_timing_ambitious + Sd_timing_ambitious),
                width = 0.2, position = position_dodge(width = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item4 loyal
item_wise_response_time_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_timing_loyal)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_timing_loyal - Sd_timing_loyal, ymax = Mean_timing_loyal + Sd_timing_loyal),
                width = 0.2, position = position_dodge(width = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item5 sensitive
item_wise_response_time_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_timing_sensitive)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_timing_sensitive - Sd_timing_sensitive, ymax = Mean_timing_sensitive + Sd_timing_sensitive),
                width = 0.2, position = position_dodge(width = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item6 warm
item_wise_response_time_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_timing_warm)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_timing_warm - Sd_timing_warm, ymax = Mean_timing_warm + Sd_timing_warm),
                width = 0.2, position = position_dodge(width = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item7 compassionate
item_wise_response_time_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_timing_compassionate)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_timing_compassionate - Sd_timing_compassionate, ymax = Mean_timing_compassionate + Sd_timing_compassionate),
                width = 0.2, position = position_dodge(width = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item8 adaptable
item_wise_response_time_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_timing_adaptable)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_timing_adaptable - Sd_timing_adaptable, ymax = Mean_timing_adaptable + Sd_timing_adaptable),
                width = 0.2, position = position_dodge(width = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item9 sincere
item_wise_response_time_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_timing_sincere)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_timing_sincere - Sd_timing_sincere, ymax = Mean_timing_sincere + Sd_timing_sincere),
                width = 0.2, position = position_dodge(width = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item10 reliable
item_wise_response_time_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_timing_reliable)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_timing_reliable - Sd_timing_reliable, ymax = Mean_timing_reliable + Sd_timing_reliable),
                width = 0.2, position = position_dodge(width = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item11 truthful
item_wise_response_time_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_timing_truthful)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_timing_truthful - Sd_timing_truthful, ymax = Mean_timing_truthful + Sd_timing_truthful),
                width = 0.2, position = position_dodge(width = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
```{r average item score by group}
mean_item_rating_bygroup <- new_df %>% 
  group_by(Group) %>% 
  summarise(Mean_item1_leader = mean(item1_leader), Sd_item1_leader = sd(item1_leader),
            Mean_item2_independent = mean(item2_independent), Sd_item2_independent = sd(item2_independent),
            Mean_item3_ambitious = mean(item3_ambitious), Sd_item3_ambitious = sd(item3_ambitious),
            Mean_item4_loyal = mean(item4_loyal), Sd_item4_loyal = sd(item4_loyal),
            Mean_item5_sensitive = mean(item5_sensitive), Sd_item5_sensitive = sd(item5_sensitive),
            Mean_item6_warm = mean(item6_warm), Sd_item6_warm = sd(item6_warm),
            Mean_item7_compassionate = mean(item7_compassionate), Sd_item7_compassionate = sd(item7_compassionate),
            Mean_item8_adaptable = mean(item8_adaptable), Sd_item8_adaptable = sd(item8_adaptable),
            Mean_item9_sincere = mean(item9_sincere), Sd_item9_sincere = sd(item9_sincere),
            Mean_item10_reliable = mean(item10_reliable), Sd_item10_reliable = sd(item10_reliable),
            Mean_item11_truthful = mean(item11_truthful), Sd_item11_truthful = sd(item11_truthful))
mean_item_rating_bygroup

## histogram
mean_item_rating_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_item1_leader)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_item1_leader - Sd_item1_leader, ymax = Mean_item1_leader + Sd_item1_leader),
                width = 0.2, position = position_dodge(width = 0.5)) +
  ylim(0, 8) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item1 leader
mean_item_rating_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_item2_independent)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_item2_independent - Sd_item2_independent, ymax = Mean_item2_independent + Sd_item2_independent),
                width = 0.2, position = position_dodge(width = 0.5)) +
  ylim(0, 8) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#item2 independent
mean_item_rating_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_item2_independent)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_item2_independent - Sd_item2_independent, ymax = Mean_item2_independent + Sd_item2_independent),
                width = 0.2, position = position_dodge(width = 0.5)) +
  ylim(0, 8) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item3 ambitious
mean_item_rating_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_item3_ambitious)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_item3_ambitious - Sd_item3_ambitious, ymax = Mean_item3_ambitious + Sd_item3_ambitious),
                width = 0.2, position = position_dodge(width = 0.5)) +
  ylim(0, 8) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item4 loyal
mean_item_rating_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_item4_loyal)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_item4_loyal - Sd_item4_loyal, ymax = Mean_item4_loyal + Sd_item4_loyal),
                width = 0.2, position = position_dodge(width = 0.5)) +
  ylim(0, 8) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item5 sensitive
mean_item_rating_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_item5_sensitive)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_item5_sensitive - Sd_item5_sensitive, ymax = Mean_item5_sensitive + Sd_item5_sensitive),
                width = 0.2, position = position_dodge(width = 0.5)) +
  ylim(0, 8) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item6 warm
mean_item_rating_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_item6_warm)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_item6_warm - Sd_item6_warm, ymax = Mean_item6_warm + Sd_item6_warm),
                width = 0.2, position = position_dodge(width = 0.5)) +
  ylim(0, 8) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item7 compassionate
mean_item_rating_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_item7_compassionate)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_item7_compassionate - Sd_item7_compassionate, ymax = Mean_item7_compassionate + Sd_item7_compassionate),
                width = 0.2, position = position_dodge(width = 0.5)) +
  ylim(0, 8) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item8 adaptable
mean_item_rating_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_item8_adaptable)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_item8_adaptable - Sd_item8_adaptable, ymax = Mean_item8_adaptable + Sd_item8_adaptable),
                width = 0.2, position = position_dodge(width = 0.5)) +
  ylim(0, 8) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item9 sincere
mean_item_rating_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_item9_sincere)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_item9_sincere - Sd_item9_sincere, ymax = Mean_item9_sincere + Sd_item9_sincere),
                width = 0.2, position = position_dodge(width = 0.5)) +
  ylim(0, 8) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item10 reliable
mean_item_rating_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_item10_reliable)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_item10_reliable - Sd_item10_reliable, ymax = Mean_item10_reliable + Sd_item10_reliable),
                width = 0.2, position = position_dodge(width = 0.5)) +
  ylim(0, 8) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# item11 truthful
mean_item_rating_bygroup %>% 
  ggplot(aes(x = Group, y = Mean_item11_truthful)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean_item11_truthful - Sd_item11_truthful, ymax = Mean_item11_truthful + Sd_item11_truthful),
                width = 0.2, position = position_dodge(width = 0.5)) +
  ylim(0, 8) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
```{r click count}
new_df <- new_df %>% 
  mutate(sum_click_count = click_count_leader + click_count_independent + click_count_ambitious + click_count_loyal +
                      click_count_sensitive + click_count_warm + click_count_compassionate + click_count_adaptable +
                      click_count_sincere + click_count_reliable + click_count_truthful)

Mean_total_click_count <- new_df %>% 
  group_by(Group) %>% 
  summarise(Mean =  mean(sum_click_count), Sd = sd(sum_click_count))
Mean_total_click_count

Mean_total_click_count %>% 
  ggplot(aes(x = Group, y = Mean)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

Mean_click_count <- new_df %>% 
  group_by(Group) %>% 
  summarise(mean_cc_leader = mean(click_count_leader), sd_cc_leader = sd(click_count_leader),
            mean_cc_independent = mean(click_count_independent), sd_cc_independent = sd(click_count_independent),
            mean_cc_ambitious = mean(click_count_ambitious), sd_cc_ambitious = sd(click_count_ambitious),
            mean_cc_loyal = mean(click_count_loyal), sd_cc_loyal = sd(click_count_loyal),
            mean_cc_sensitive = mean(click_count_sensitive), sd_cc_sensitive = sd(click_count_sensitive),
            mean_cc_warm = mean(click_count_warm), sd_cc_warm = sd(click_count_warm),
            mean_cc_compassionate = mean(click_count_compassionate), sd_cc_compassionate = sd(click_count_compassionate),
            mean_cc_adaptable = mean(click_count_adaptable), sd_cc_adaptable = sd(click_count_adaptable),
            mean_cc_sincere = mean(click_count_sincere), sd_cc_sincere = sd(click_count_sincere),
            mean_cc_reliable = mean(click_count_reliable), sd_cc_reliable = sd(click_count_reliable),
            mean_cc_truthful = mean(click_count_truthful), sd_cc_truthful = sd(click_count_truthful))

Mean_click_count
```


```{r Hypothesis 1}
H1_m <- aov(masculinity ~ Group, data = new_df)
summary(H1_m)
# ANOVA indicates no difference among groups but still running Post-hoc
TukeyHSD(H1_m)

H1_f <- aov(femininity ~ Group, data = new_df)
summary(H1_f)
TukeyHSD(H1_f)
```
```{r Hypothesis 2}
H2 <- manova(cbind(masculinity, femininity) ~ Group, data = new_df)
summary(H2)
```

```{r Hypothesis 3: testing for response time}
## masculinity & femininity ratings
H3_m <- aov(masculinity ~ Group, data = new_df)
summary(H3_m)
# ANOVA indicates no difference among groups but still running Post-hoc
TukeyHSD(H3_m)

H3_f <- aov(femininity ~ Group, data = new_df)
summary(H3_f)
TukeyHSD(H3_f)

## total response time difference
total_response_time_anova <- aov(total_response_time ~ Group, data = new_df)
summary(total_response_time_anova)
TukeyHSD(total_response_time_anova) 

## item-wise response time difference
item1_response_time_aonva <- aov(timing_leader ~ Group, data = new_df)
summary(item1_response_time_aonva)

item2_response_time_aonva <- aov(timing_independent ~ Group, data = new_df)
summary(item2_response_time_aonva)

item3_response_time_aonva <- aov(timing_ambitious ~ Group, data = new_df)
summary(item3_response_time_aonva)

item4_response_time_aonva <- aov(timing_loyal ~ Group, data = new_df)
summary(item4_response_time_aonva)

item5_response_time_aonva <- aov(timing_sensitive ~ Group, data = new_df)
summary(item5_response_time_aonva)

item6_response_time_aonva <- aov(timing_warm ~ Group, data = new_df)
summary(item6_response_time_aonva)

item7_response_time_aonva <- aov(timing_compassionate ~ Group, data = new_df)
summary(item7_response_time_aonva)

item8_response_time_aonva <- aov(timing_adaptable ~ Group, data = new_df)
summary(item8_response_time_aonva)

item9_response_time_aonva <- aov(timing_sincere ~ Group, data = new_df)
summary(item9_response_time_aonva)

item10_response_time_aonva <- aov(timing_reliable ~ Group, data = new_df)
summary(item10_response_time_aonva)

item11_response_time_aonva <- aov(timing_truthful ~ Group, data = new_df)
summary(item11_response_time_aonva)
```
# Hypothesis 3 was not supported
# H3a: No difference in masculinity or femininity rating among groups
# H3b: No difference in response time

```{r}
lm_df <- new_df %>% 
  mutate(eth = as.factor(dem3_ethnicity),
         emp_st = as.factor(dem4_employment_status),
         tot_res_time = total_response_time,
         age = dem1_age,
         gender = dem2_gender)

model <- lm(tot_res_time ~ Group * age * gender * eth * emp_st, data = lm_df)
summary(model)

model1 <- lm(tot_res_time ~ Group * age * gender, data = lm_df)
summary(model1)

model2 <- lm(tot_res_time ~ Group * eth * emp_st, data = lm_df)
summary(model2)
```











